### PR TITLE
Added support for RequireJS

### PR DESCRIPTION
**Pull request by mdcone**
Changes made to the header and footer in the npm/lib directory wrap the npm version of jsrsasign in code which allows for both RequireJS and CommonJS loaders to run this module. Note that the the npm/lib/jsrsasign.js file still needs to be rebuilt before pushing up to npm.

### CODE REVIEW

**Comment by mdcone** [comment]
Hey, @kjur do these changes look acceptable to you? Thanks!

**Comment by kjur** [comment]
Hi, it's acceptable but it has different newline or indentation. So I need to make a patch later.

**Comment by huma-hamid** [comment]
Is this issue still pending? I am currently using a locally patched jsrsasign version to work with RequireJS, it would be really nice if I don't have to do that anymore and jsrsasign automatically supports it.

**Comment by kjur** [comment]
@huma-hamid , I need this patch for current version.

**Comment by jean-moldovan** [comment]
Hello, any plans on pushing these changes ? Would be really nice to have RequireJs support.

**Comment by huma-hamid** [comment]
@kjur - Our team gave up on RequireJS patched version and now only using the commonjs version. The patch I am talking about, was a local fix, created by @mdcone. I think it would be nice if we don't have to use a patch file and get the actual RequireJS support.

**Comment by ashishtilara** [comment]
+1

**Comment by kjur** [comment]
The patch is conflicting. So I close this ticket.

**Pull request closed without merging**
