### PR TITLE
Fixed the order of the minified files in the Makefile

### PR DESCRIPTION
**Pull request by lionello**
The `jsrsasign-header.js` was added to generate the same content as currently.

### CODE REVIEW

**Comment by Ruffio** [comment]
@lionello What is the issue with the current Makefile?

**Comment by lionello** [comment]
@Ruffio The order of the files was not deterministic in the old Makefile, resulting in huge diffs depending who would run it. By fixing the files, and their order, the diff is very small and only shows the actual changes.

**Comment by Ruffio** [comment]
@lionello so it is fixed now, or is it only in your PR that it is fixed?

**Comment by lionello** [comment]
It's not fixed. My PR fixes it.

**Comment by Ruffio** [comment]
@kjur if the conflict is resolved, can this PR be merged?

**Comment by kjur** [comment]
Thank you for pull request. Makefile was changed.

**Pull request closed without merging**
