### PR TITLE
A fix for jsrsasign issue #270, removing duplicate export of "b64tohex"

### PR DESCRIPTION
**Pull request by DonGissel**
The title says it all, really. Fixes issue #270.

### CODE REVIEW

**Comment by kjur** [comment]
Thank you for your pull request. I've fixed it in the next version. Thanks.

**Comment by DonGissel** [comment]
You're welcome. When is the next version coming out? I kind of need it. ;-)

**Comment by kjur** [comment]
In a few days. It's under final check.

**Comment by kjur** [comment]
I've released fixed version as 8.0.0. Thanks.

**Pull request closed without merging**
