### PR TITLE
Support issuer values with '/' chars.

### PR DESCRIPTION
**Pull request by cblair**
See https://github.com/kjur/jsrsasign/issues/119.

kjur, see the AUT additions for usage on these enhancements.

### CODE REVIEW

**Comment by kjur** [comment]
Hi @cblair , I've released 4.9.1. Thanks.
https://github.com/kjur/jsrsasign/releases

**Comment by cblair** [comment]
Thanks kjur! I didn't see the added function and code in jsrsasign-4.9.1-all-min.js and npm/lib/jsrsasign.js though, am I missing something?

**Comment by kjur** [comment]
Sorry, I'll check later.

**Comment by kjur** [comment]
I've released 4.9.2 and its npm packages. I think this solve the issue :) Thanks.

**Comment by cblair** [comment]
I've verified it works, thanks!!

**Pull request merged**
