### PR TITLE
JWK from X509 certificate

### PR DESCRIPTION
**Pull request by cplussharp**
including "x5c", "x5t" and "x5t#S256"

also load X509 from JWK

### CODE REVIEW

**Comment by kjur** [comment]
Hi @cplussharp , thank you kindly for your PR.

**Comment by kjur** [comment]
Hi @cplussharp, I don't want to affect JWK to X509 class. So this function may be moved to this kind of methods to KEYUTIL.getJWK* in the next release.

**Comment by cplussharp** [comment]
That's OK. I was not sure where to place the functionality. KEYUTIL.getJWK* was also my first idea, but for easier development I placed in directly in X509. ;-)
Btw. there is no getFingerprint() method in X509. Should I made a PR to introduce it? Maybe with the algorithm as parameter and the default would be "sha1"?

**Comment by kjur** [comment]
Thank you @cplussharp . As for fingerprint, is this good for you?
https://kjur.github.io/jsrsasign/api/symbols/KJUR.jws.JWS.html#.getJWKthumbprint

**Comment by cplussharp** [comment]
Sorry that question was a little bit missleading here. I meant the X509 fingerprint.

**Comment by kjur** [comment]
Hi @cplussharp , I've released 10.5.1 update today including your PRs.
Thank you indeed for your great contributions.
I've done some modification for your PRs:
- move X509.getPublicKeyJWK to KEYUTIL.getJWK
- readCertJWK removed because not so much effort required
- qunit-do-x509-jwk.html removed and some tests in it were moved to qunit-do-keyutil-jwk.html

**Pull request merged**
