### PR TITLE
Fixed the npm_util Makefile for better portability

### PR DESCRIPTION
**Pull request by lionello**
For example, using `.PHONY` and proper dependencies.

### CODE REVIEW

**Comment by Ruffio** [comment]
@lionello Are there any issues currently with the Makefile as it is currently?

**Comment by lionello** [comment]
@Ruffio The Makefile target doesn't actually specify the output it's supposed to create and didn't specify any dependencies either.

**Comment by Ruffio** [comment]
@kjur Can this be merged?

**Comment by Ruffio** [comment]
@kjur Can this be merged?

**Comment by Ruffio** [comment]
@kjur Can this be merged?

**Comment by Ruffio** [comment]
@kjur what is holding this PR back?

**Comment by kjur** [comment]
Thank you @lionello

**Pull request merged**
