### PR TITLE
Brainpool Curves for ECDSA

### PR DESCRIPTION
**Pull request by forlemon**
Brainpool curves support for ECDSA (definitions and OIDs)

### CODE REVIEW

**Comment by kjur** [comment]
Hello @forlemon , thank you for your pull request. Did you test interoperability with other implementations such as OpenSSL.

**Comment by forlemon** [comment]
Hello @kjur, I did not, I'll look into it and test it.

Also, I forgot to add the OIDs to the  KJUR.crypto.ECDSA.getName() function, I'll add it too.

**Comment by forlemon** [comment]
Interoperability with brainpool p256, p384 and p512 is most likely garanteed because it is part of the TLS standard, the other curves I will look into it. In the worst case I'll just leave these 3 curves.

**Comment by kjur** [comment]
Thank you @forlemon . When I write test case and verify interoperability, I'll merge your pull request.

**Comment by forlemon** [comment]
No problem @kjur. I can create tests on the [qunit-do-crypto-ecdsa.html](https://github.com/kjur/jsrsasign/blob/master/test/qunit-do-crypto-ecdsa.html) tests script, using signatures created with OpenSSL with each curve I defined. Would this be sufficient to prove interoperability?

**Comment by kjur** [comment]
It's great!! Thank you @forlemon . Could you make other test case file such as qunit-do-crypto-ecdsa-bp.html for brainpool test cases.

**Comment by forlemon** [comment]
Yes I can @kjur! Another thing I've noticed, secp521r1 curve is defined but not used, why is that? I can add it in this PR if you want too. 
Here in Europe the secp256, 384 and 521 and brainpool256, 384 and 512 are the ones that are used in the majority of cases.

**Comment by kjur** [comment]
Hi @forlemon , ECDSA implementation of jsrsasign is based on 
Stefan Thomas's Bitcoin JavaScript library.
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/ecdsa.js
It seem that large key is not supported such as P-521.
I need further investigation to support P-521.

**Comment by kjur** [comment]
This request is not be accepted since brainpool256, 384 and 512 algorithm implementation and its test code is not provided at this stage. Thank you for understanding.

**Pull request closed without merging**
