### PR TITLE
try to fix error regression from 10.4.1

### PR DESCRIPTION
**Pull request by topce**
error loading discovery document ReferenceError: assignment to undeclared variable hPub
    generateKeyPairHex jsrsasign.js:235
    generateKeypair jsrsasign.js:238
    load key-store.service.ts:37

### CODE REVIEW

**Comment by kjur** [comment]
Hi @topce , thank you for your PR.

**Comment by topce** [comment]
Welcome  ;-)
Thank you for great library  !
Is it possible to publish 10.5.1 to npm?

**Comment by kjur** [comment]
I may wait PRs for #526 and #525 if possible.

**Comment by topce** [comment]
no problem 
thank you!

**Comment by kjur** [comment]
Hi @topce , I've released 10.5.1 with your PR today. Thank you.

**Pull request merged**
